# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "adm$reference_values", :id => false, :force => true do |t|
    t.column "aref_title",        :string, :limit => 30,   :null => false
    t.column "value",             :string, :limit => 30,   :null => false
    t.column "valid_type_values", :string, :limit => 1000, :null => false
    t.column "err_message",       :string, :limit => 200
  end

  add_index "adm$reference_values", ["aref_title"], :name => "arefv_aref_fk_i"

  create_table "adm$references", :primary_key => "title", :force => true do |t|
    t.column "data_table",        :string, :limit => 30, :null => false
    t.column "const_table",       :string, :limit => 30, :null => false
    t.column "const_pk_column",   :string, :limit => 30, :null => false
    t.column "const_type_column", :string, :limit => 30, :null => false
  end

  create_table "container_element_rules", :id => false, :force => true do |t|
    t.column "min_occurances", :integer,  :limit => 5,  :precision => 5,  :scale => 0
    t.column "max_occurances", :integer,  :limit => 5,  :precision => 5,  :scale => 0
    t.column "element_id",     :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "container_id",   :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "created_at",     :datetime, :limit => 6
    t.column "updated_at",     :datetime, :limit => 6
  end

  add_index "container_element_rules", ["container_id"], :name => "cel_obt_fk_i"
  add_index "container_element_rules", ["element_id"], :name => "cel_obt_include_fk_i"

  create_table "container_elements", :id => false, :force => true do |t|
    t.column "elorder",      :integer,  :limit => 5,  :precision => 5,  :scale => 0,                    :null => false
    t.column "element_id",   :integer,  :limit => 12, :precision => 12, :scale => 0,                    :null => false
    t.column "container_id", :integer,  :limit => 12, :precision => 12, :scale => 0,                    :null => false
    t.column "main",         :boolean,                :precision => 1,  :scale => 0, :default => false, :null => false
    t.column "created_at",   :datetime, :limit => 6
    t.column "updated_at",   :datetime, :limit => 6
  end

  add_index "container_elements", ["elorder", "container_id"], :name => "coe_obc_order_uk_uk", :unique => true
  add_index "container_elements", ["container_id"], :name => "coe_obj_fk_i"
  add_index "container_elements", ["element_id"], :name => "coe_obj_have_as_item_fk_i"

  create_table "content_types", :force => true do |t|
    t.column "ext",           :string,   :limit => 10,                                 :null => false
    t.column "mime_junior",   :string,   :limit => 50,                                 :null => false
    t.column "application",   :string,   :limit => 200
    t.column "label_id",      :integer,  :limit => 12,  :precision => 12, :scale => 0, :null => false
    t.column "media_type_id", :integer,  :limit => 12,  :precision => 12, :scale => 0, :null => false
    t.column "created_at",    :datetime, :limit => 6
    t.column "updated_at",    :datetime, :limit => 6
  end

  add_index "content_types", ["ext"], :name => "cty_ext_uk", :unique => true
  add_index "content_types", ["label_id"], :name => "cty_lbl_fk_i"
  add_index "content_types", ["media_type_id"], :name => "cty_mty_fk_i"

  create_table "files_on_storages", :force => true do |t|
    t.column "object_id",  :integer,  :limit => 12,   :precision => 12, :scale => 0
    t.column "storage_id", :integer,  :limit => 12,   :precision => 12, :scale => 0, :null => false
    t.column "created_at", :datetime, :limit => 6
    t.column "updated_at", :datetime, :limit => 6
    t.column "filename",   :string,   :limit => 1000,                                :null => false
  end

  add_index "files_on_storages", ["object_id"], :name => "flo_obj_define_location_of_f_i"
  add_index "files_on_storages", ["storage_id"], :name => "flo_str_fk_i"

  create_table "items", :force => true do |t|
    t.column "type",            :string,   :limit => 30,                                                          :null => false
    t.column "id3",             :text
    t.column "md5",             :string,   :limit => 32
    t.column "content_size",    :decimal
    t.column "created_at",      :datetime, :limit => 6
    t.column "updated_at",      :datetime, :limit => 6
    t.column "mask",            :boolean,                :precision => 1,  :scale => 0, :default => true,         :null => false
    t.column "state",           :string,   :limit => 30,                                :default => "DraftState", :null => false
    t.column "object_type_id",  :integer,  :limit => 12, :precision => 12, :scale => 0,                           :null => false
    t.column "content_type_id", :integer,  :limit => 12, :precision => 12, :scale => 0
    t.column "text",            :text
    t.column "label_id",        :integer,  :limit => 12, :precision => 12, :scale => 0
  end

  add_index "items", ["object_type_id"], :name => "obj_obt_be_desribed_by_fk_i"

  create_table "items_labels", :id => false, :force => true do |t|
    t.column "item_id",    :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "label_id",   :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "created_at", :datetime, :limit => 6
    t.column "updated_at", :datetime, :limit => 6
  end

  add_index "items_labels", ["label_id"], :name => "lbl_obj_lbl_fk_i"
  add_index "items_labels", ["item_id"], :name => "lbl_obj_obj_fk_i"

  create_table "label_descs", :force => true do |t|
    t.column "value",       :string,   :limit => 2000,                                :null => false
    t.column "label_id",    :integer,  :limit => 12,   :precision => 12, :scale => 0, :null => false
    t.column "language_id", :integer,  :limit => 12,   :precision => 12, :scale => 0, :null => false
    t.column "created_at",  :datetime, :limit => 6
    t.column "updated_at",  :datetime, :limit => 6
  end

  add_index "label_descs", ["label_id", "language_id"], :name => "lbd_ik", :unique => true
  add_index "label_descs", ["language_id"], :name => "lbd_lan_fk_i"
  add_index "label_descs", ["label_id"], :name => "lbd_lbl_fk_i"

  create_table "label_type_descs", :force => true do |t|
    t.column "value",                :string,   :limit => 100,                                :null => false
    t.column "language_id",          :integer,  :limit => 12,  :precision => 12, :scale => 0, :null => false
    t.column "label_type_id",        :integer,  :limit => 12,  :precision => 12, :scale => 0, :null => false
    t.column "object_rule_label_id", :integer,  :limit => 12,  :precision => 12, :scale => 0
    t.column "created_at",           :datetime, :limit => 6
    t.column "updated_at",           :datetime, :limit => 6
  end

  add_index "label_type_descs", ["language_id"], :name => "ltd_lan_fk_i"
  add_index "label_type_descs", ["label_type_id", "language_id", "object_rule_label_id"], :name => "ltd_ltd_uk_uk", :unique => true
  add_index "label_type_descs", ["label_type_id"], :name => "ltd_lty_fk_i"
  add_index "label_type_descs", ["object_rule_label_id"], :name => "ltd_orl_fk_i"

  create_table "label_types", :force => true do |t|
    t.column "type",          :string,   :limit => 30,                                                    :null => false
    t.column "value_pattern", :string,   :limit => 2000
    t.column "hrid",          :string,   :limit => 30
    t.column "created_at",    :datetime, :limit => 6
    t.column "updated_at",    :datetime, :limit => 6
    t.column "restricted",    :boolean,                  :precision => 1, :scale => 0, :default => false
    t.column "is_predefined", :boolean,                  :precision => 1, :scale => 0, :default => false, :null => false
  end

  add_index "label_types", ["hrid"], :name => "lty_lty_hrid_uk_uk", :unique => true

  create_table "labels", :force => true do |t|
    t.column "type",          :string,   :limit => 30,                                :null => false
    t.column "hrid",          :string,   :limit => 30
    t.column "numbervalue",   :decimal
    t.column "datevalue",     :datetime
    t.column "label_type_id", :integer,  :limit => 12, :precision => 12, :scale => 0
    t.column "created_at",    :datetime, :limit => 6
    t.column "updated_at",    :datetime, :limit => 6
  end

  add_index "labels", ["hrid"], :name => "lbl_lbl_hrid_uk_uk", :unique => true
  add_index "labels", ["label_type_id"], :name => "lbl_lty_fk_i"

  create_table "languages", :force => true do |t|
    t.column "abbr",       :string,   :limit => 3,                                 :null => false
    t.column "label_id",   :integer,  :limit => 12, :precision => 12, :scale => 0
    t.column "created_at", :datetime, :limit => 6
    t.column "updated_at", :datetime, :limit => 6
  end

  add_index "languages", ["abbr"], :name => "lan_lan_uk_uk", :unique => true
  add_index "languages", ["label_id"], :name => "lan_lbl_fk_i"

  create_table "media_types", :force => true do |t|
    t.column "media_type", :string,   :limit => 50,                                :null => false
    t.column "label_id",   :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "created_at", :datetime, :limit => 6
    t.column "updated_at", :datetime, :limit => 6
  end

  add_index "media_types", ["label_id"], :name => "mty_lbl_fk_i"
  add_index "media_types", ["media_type"], :name => "mty_uk", :unique => true

  create_table "mount_points", :force => true do |t|
    t.column "mount_point",      :string,   :limit => 2000, :null => false
    t.column "oracle_directory", :string,   :limit => 30
    t.column "created_at",       :datetime, :limit => 6
    t.column "updated_at",       :datetime, :limit => 6
  end

  add_index "mount_points", ["mount_point"], :name => "omp_uk", :unique => true

  create_table "object_link_types", :force => true do |t|
    t.column "label_id",         :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "label_reverse_id", :integer,  :limit => 12, :precision => 12, :scale => 0
    t.column "created_at",       :datetime, :limit => 6
    t.column "updated_at",       :datetime, :limit => 6
  end

  add_index "object_link_types", ["label_reverse_id"], :name => "olt_lbl_fk_i"
  add_index "object_link_types", ["label_id"], :name => "olt_lbl_have_as_reverse_nam__i"

  create_table "object_links", :id => false, :force => true do |t|
    t.column "object_id",           :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "object_linked_id",    :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "object_link_type_id", :integer,  :limit => 12, :precision => 12, :scale => 0, :null => false
    t.column "created_at",          :datetime, :limit => 6
    t.column "updated_at",          :datetime, :limit => 6
  end

  add_index "object_links", ["object_linked_id"], :name => "obl_obj_fk_i"
  add_index "object_links", ["object_id"], :name => "obl_obj_have_as_2nd_fk_i"
  add_index "object_links", ["object_link_type_id"], :name => "obl_olt_fk_i"

  create_table "object_rule_labels", :force => true do |t|
    t.column "label_order",          :integer,  :limit => 5,    :precision => 5,  :scale => 0, :null => false
    t.column "occ_min",              :integer,  :limit => 5,    :precision => 5,  :scale => 0
    t.column "occ_max",              :integer,  :limit => 5,    :precision => 5,  :scale => 0
    t.column "value_pattern",        :string,   :limit => 2000
    t.column "label_id",             :integer,  :limit => 12,   :precision => 12, :scale => 0
    t.column "label_type_id",        :integer,  :limit => 12,   :precision => 12, :scale => 0, :null => false
    t.column "object_type_id",       :integer,  :limit => 12,   :precision => 12, :scale => 0, :null => false
    t.column "created_at",           :datetime, :limit => 6
    t.column "updated_at",           :datetime, :limit => 6
    t.column "label_type_action_id", :string,   :limit => 30
  end

  add_index "object_rule_labels", ["label_id"], :name => "orl_lbl_fk_i"
  add_index "object_rule_labels", ["label_type_id"], :name => "orl_lty_fk_i"
  add_index "object_rule_labels", ["object_type_id"], :name => "orl_obt_fk_i"
  add_index "object_rule_labels", ["label_order"], :name => "orl_orl_order_uk_uk", :unique => true
  add_index "object_rule_labels", ["object_type_id", "label_type_id"], :name => "orl_uk", :unique => true

  create_table "object_types", :force => true do |t|
    t.column "type",               :string,   :limit => 30,                                                     :null => false
    t.column "hrid",               :string,   :limit => 30,                                                     :null => false
    t.column "content_pattern",    :string,   :limit => 1000
    t.column "label_id",           :integer,  :limit => 12,   :precision => 12, :scale => 0,                    :null => false
    t.column "is_all_obc_allowed", :boolean,                  :precision => 1,  :scale => 0
    t.column "is_all_lbl_allowed", :boolean,                  :precision => 1,  :scale => 0, :default => false, :null => false
    t.column "is_all_obl_allowed", :boolean,                  :precision => 1,  :scale => 0, :default => false, :null => false
    t.column "content_type_id",    :integer,  :limit => 12,   :precision => 12, :scale => 0
    t.column "media_type_id",      :integer,  :limit => 12,   :precision => 12, :scale => 0
    t.column "created_at",         :datetime, :limit => 6
    t.column "updated_at",         :datetime, :limit => 6
  end

  add_index "object_types", ["label_id"], :name => "obt_lbl_fk_i"
  add_index "object_types", ["hrid"], :name => "obt_obt_uk_uk", :unique => true

  create_table "physical_locations", :force => true do |t|
    t.column "numb",                 :string,   :limit => 30,                                 :null => false
    t.column "title",                :string,   :limit => 100,                                :null => false
    t.column "description",          :string,   :limit => 500
    t.column "physical_location_id", :integer,  :limit => 12,  :precision => 12, :scale => 0
    t.column "created_at",           :datetime, :limit => 6
    t.column "updated_at",           :datetime, :limit => 6
  end

  add_index "physical_locations", ["physical_location_id"], :name => "phl_fk_i"
  add_index "physical_locations", ["numb", "physical_location_id"], :name => "sto_uk", :unique => true

  create_table "storages", :force => true do |t|
    t.column "type",                 :string,   :limit => 30,                                 :null => false
    t.column "tape_type",            :string,   :limit => 30
    t.column "offline_label",        :string,   :limit => 30
    t.column "read_only",            :boolean,                 :precision => 1,  :scale => 0
    t.column "protocol",             :string,   :limit => 30
    t.column "host",                 :string,   :limit => 100
    t.column "path_to_root",         :string,   :limit => 100
    t.column "title",                :string,   :limit => 30
    t.column "created_at",           :datetime, :limit => 6
    t.column "updated_at",           :datetime, :limit => 6
    t.column "physical_location_id", :integer,  :limit => 12,  :precision => 12, :scale => 0
    t.column "mount_point_id",       :integer,  :limit => 12,  :precision => 12, :scale => 0
    t.column "is_default",           :boolean,                 :precision => 1,  :scale => 0
  end

  add_index "storages", ["offline_label", "type"], :name => "str_off_uk", :unique => true
  add_index "storages", ["mount_point_id"], :name => "str_omp_fk_i"
  add_index "storages", ["title"], :name => "str_onl_uk", :unique => true
  add_index "storages", ["physical_location_id"], :name => "str_sto_fk_i"

end
